---

- name: restart network
  service: name=network state=restarted
  sudo: yes

- name: remove require tty
  lineinfile: regexp="^\w+\s+requiretty" dest=/etc/sudoers state=absent
  sudo: yes

- name: configure the timezone
  sudo: yes
  file: src=/usr/share/zoneinfo/UTC dest=/etc/localtime state=link force=yes backup=yes

- name: set english
  sudo: yes
  copy: src=i18n dest=/etc/sysconfig/i18n
